# Site Settings
title: Juunone | for dev blog
email: juunone@gmail.com
description: juunone's dev blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-131472455-1"

# User Settings
username: 최 준원
usernickname: Juunone
user_description: Front-End Developer
disqus_username: https-juunone-github-io

# Social Media
# Remove the item if you don't need it
github_username: juunone
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: choijunewon
# linkedin_username: juunone
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Tags
    url: /tags/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ["package.json", "src", "node_modules"]
